import type { Metadata } from 'next';
import './globals.css';
import { inter } from '@/app/lib/fonts';
import { ThemeProvider } from 'next-themes';
import ReactQueryProvider from './react-query-provider';

export const metadata: Metadata = {
  title: {
    template: '%s | Social App',
    default: 'Social App',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={inter.className}>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
